FROM python:3.7

RUN mkdir /api
WORKDIR /api
COPY requirements.txt /api/
COPY . /api
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install -r requirements.txt
EXPOSE 8000
CMD ["uwsig","--ini","uwsgi-ini"]